[project]
name = "drone-path-optimizer"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.7",
  "osmnx>=1.9",
  "shapely>=2.0",
  "pyproj>=3.6",
]
